### ISSUE TITLE
add support for newer node versions

### ISSUE THREAD

**Issue by beuluis** [ddsol/speedtest.net#114]
Node 14.8.0 fails on install with:

```console
> lzma-native@4.0.6 install /Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for lzma-native@4.0.6 and node@14.8.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/14.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/lzma-native
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/14.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64/lzma_native.node --module_name=lzma_native --module_path=/Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/14.8.0/bin/node" "/Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/lzma-native
node-pre-gyp ERR! node -v v14.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/14.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64/lzma_native.node --module_name=lzma_native --module_path=/Users/beuluis/workspaces/github/speedtester/speedtester-api/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN enoent ENOENT: no such file or directory, open '/Users/beuluis/workspaces/github/speedtester/speedtester-api/package.json'
npm WARN speedtester-api No description
npm WARN speedtester-api No repository field.
npm WARN speedtester-api No README data
npm WARN speedtester-api No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@4.0.6 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzma-native@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/beuluis/.npm/_logs/2020-10-26T19_52_52_239Z-debug.log
```

**Comment by Nicobas** [comment]
I have the same issue on centos but it works on macos

**Comment by karelkryda** [comment]
Someone solved this issue? I can't install on W10 also can't install on RPi.
Please I will be happy if someone will help me

**Comment by dtmarangoni** [comment]
Hello,

I have the same issue. Is there any workaround or solution to this?

Thanks.
BR,
Daniel.

**Comment by chrisspiegl** [comment]
I just tried running this on macOS (Intel) with Node version 16.13 and it fails as well?
Any way to fix this?
