### ISSUE TITLE
lzma-native version is outdated and broken for global installs.

### ISSUE THREAD

**Issue by voidf1sh** [ddsol/speedtest.net#124]
Installing the module in WSL Ubuntu globally. The version of `lzma-native` required by this package (4.0.6) is severely out of date (current is 8.0.1), this out of date version of `lzma-native` has not been updated to use the new version of `node-pre-gyp` (`@mapbox/node-pre-gyp`), this results in a failed global install for CLI usage.

```
$ sudo npm install --global speedtest-net
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
/usr/local/bin/speedtest-net -> /usr/local/lib/node_modules/speedtest-net/bin/index.js

> lzma-native@4.0.6 install /usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for lzma-native@4.0.6 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v64-linux-x64'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/build'
gyp ERR! System Linux 4.4.0-19041-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v64-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v64-linux-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v64-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v64-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/speedtest-net/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.4.0-19041-Microsoft
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/speedtest-net/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v64-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v64-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@4.0.6 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by RoninActual** [comment]
duplicate #114
