### ISSUE TITLE
error running speed-test: "Cannot read property 'settings' of null"

### ISSUE THREAD

**Issue by babelthuap** [ddsol/speedtest.net#17]
I get the following when I run [speed-test](https://github.com/sindresorhus/speed-test). It appears to be a problem with speedtest-net, no?

```
$ speed-test
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'settings' of null
    at gotServers (~/.nvm/versions/node/v5.0.0/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:465:22)
    at ~/.nvm/versions/node/v5.0.0/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:43:22
    at ~/.nvm/versions/node/v5.0.0/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:226:13
    at Parser.<anonymous> (~/.nvm/versions/node/v5.0.0/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:483:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.exports.Parser.Parser.parseString (~/.nvm/versions/node/v5.0.0/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:493:16)
    at Parser.parseString (~/.nvm/versions/node/v5.0.0/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (~/.nvm/versions/node/v5.0.0/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:534:19)
    at ~/.nvm/versions/node/v5.0.0/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:224:9
```

**Comment by AdrianKoshka** [comment]
If it helps any I was able to replicate this error also

```
$speed-test

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'settings' of null
    at gotServers (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:451:22)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:43:22
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:226:13
    at Parser.<anonymous> (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:483:18)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:493:16)
    at Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:534:19)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:224:9
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:43:22

```

**Comment by brettmarl** [comment]
Yeah - for some reason the old speedtest.net URL to obtain servers from is returning 200 OK and an empty response. 

http://www.speedtest.net/speedtest-servers-static.php

oddly - if you add a parameter, like:

http://www.speedtest.net/speedtest-servers-static.php?x=y 

it returns a valid server set. weird - i wonder if the 200-blank response is getting cached somewhere. 

If anyone needs a work around for now, you can initialize your speed test object this way:

```
    test = speedTest({
        maxTime: 15000 //,
        serversUrl: 'http://www.speedtest.net/speedtest-servers-static.php?r=' + Math.random()
    });

```

Hopefully this self-recovers in a day or two.

**Comment by babelthuap** [comment]
Thanks for looking into it! That works for now.

**Comment by brettmarl** [comment]
seems like speedtest.net servers are correctly returning the config info now. we can close this issue.

**Comment by ddsol** [comment]
Thanks for the debugging. If it occurs again I'll add a random parameter.
