### ISSUE TITLE
Improve error message when servers cannot be fetched

### ISSUE THREAD

**Issue by sindresorhus** [ddsol/speedtest.net#30]
The current error is not very helpful for users.

```
TypeError: Cannot read property 'settings' of null
    at gotServers (/home/travis/build/sindresorhus/speed-test/node_modules/speedtest-net/index.js:525:20)
    at /home/travis/build/sindresorhus/speed-test/node_modules/speedtest-net/index.js:48:16
    at /home/travis/build/sindresorhus/speed-test/node_modules/speedtest-net/index.js:241:7
    at Parser.<anonymous> (/home/travis/build/sindresorhus/speed-test/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.exports.Parser.Parser.parseString (/home/travis/build/sindresorhus/speed-test/node_modules/xml2js/lib/xml2js.js:499:16)
    at Parser.parseString (/home/travis/build/sindresorhus/speed-test/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/home/travis/build/sindresorhus/speed-test/node_modules/xml2js/lib/xml2js.js:540:19)
    at /home/travis/build/sindresorhus/speed-test/node_modules/speedtest-net/index.js:239:5
```

-

Related issue: https://github.com/sindresorhus/speed-test/issues/27

**Comment by sindresorhus** [comment]
Thank you ❤️
