### ISSUE TITLE
No network kills test (no problem), however kills node too

### ISSUE THREAD

**Issue by pvblicltd** [ddsol/speedtest.net#6]
Hi, 

(Thanks for this plugin, it's an awesome job).

I'll have a look at this myself and try to fix, will do a pull request when I can find a solution, however any pointers would be appreciated.

I do check for connectivity before running the test, however if the network connection fails during the test, the error kills the whole app rather than returning an error.

I'll probably do an error check within the gotServers() function.. I haven't followed the code through properly yet so this may be way off.

So, just letting you know I guess :-)

Best,

J

/Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/index.js:440
        var s=servers.settings.servers[0].server;
                     ^
TypeError: Cannot read property 'settings' of null
    at gotServers (/Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/index.js:440:22)
    at /Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/index.js:43:22
    at /Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/index.js:226:13
    at Parser.<anonymous> (/Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:432:18)
    at Parser.emit (events.js:107:17)
    at Parser.exports.Parser.Parser.parseString (/Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:441:14)
    at Parser.parseString (/Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:6:59)
    at exports.parseString (/Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:483:19)
    at /Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/index.js:224:9
    at /Users/jamesgray/Sites/MOJ/sh-uptime/node_modules/speedtest-net/index.js:43:22

**Comment by ddsol** [comment]
I fixed it. It was a missing error test. Thanks for catching this.

**Comment by pvblicltd** [comment]
Awesome thank you :-)
