### ISSUE TITLE
Duplicate error on no network

### ISSUE THREAD

**Issue by jsejcksn** [ddsol/speedtest.net#81]
``` js
// st.js
const speedTest = require('speedtest-net');
const test = speedTest({maxTime: 5000});
test.on('error', err => console.error(err));
```

``` shell
$ node st.js 
{ Error: getaddrinfo ENOTFOUND www.speedtest.net www.speedtest.net:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.speedtest.net',
  host: 'www.speedtest.net',
  port: 443 }
{ Error: getaddrinfo ENOTFOUND www.speedtest.net www.speedtest.net:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.speedtest.net',
  host: 'www.speedtest.net',
  port: 443 }
```

Is this due to some type of retry?

**Comment by ddsol** [comment]
Download and upload, probably.
